### PR TITLE
fix: Disable "Se resultat" button during loading of result

### LINKED ISSUE #196: App crashes when viewing results
The app sometimes crash when pressing `Se resultat` on the screen displayed right after finishing a hearing test.

### PR DESCRIPTION
**Pull request by ofredstie**
During loading of the result after a completed test the "Se resultat" button will be disabled and display a spinner. This prevents the app from crashing when pressing the "Se resultat" button before the newly taken test has been analysed and sent to the app.

Closes #196

### CODE REVIEW

File: components/common/EDS/Button.tsx [hunk 1]
```diff
@@ -30,11 +30,18 @@ const ButtonEDS = ({
...
 }: ButtonProps) => {
   const getBackgroundColor = () => {
-    if (disabled || loading || outlined) return `#EAEAEA`;
+    if (outlined) return `#FFFFFF`;
+    if ((disabled || loading) && !outlined) return `#EAEAEA`;
     if (danger) return "#EB0000";
     return "#007079";
   };
 
+  const getTextColor = () => {
```
Comment (dansvend) [inline components/common/EDS/Button.tsx:39]: Customization of common components like Button, Input etc. should avoided in project code and should be done in a component library like mad-expo-core instead to avoid people doing the same work multiple times.

**Review by dansvend — CHANGES_REQUESTED** [review]
I left some comments on possible changes but you could also ask Adrian to get his opinions as well :)

File: components/common/EDS/Button.tsx (hunk 1 above)
Comment (ofredstie) [reply components/common/EDS/Button.tsx:39]: I agree, will change it back to the way it was. 
Looked at the expo core button and it seems that it does not support outline style yet, will bring it up at tomorrows dev meeting. Think it could a good task for me to implement this in the expo core to familiarize myself with this repo.

File: components/common/molecules/TestResultItem.tsx [hunk 2]
```diff
@@ -23,7 +23,7 @@ export const TestResultItem: React.FC<Props> = ({
   const [chartData, setChartData] = useState<ChartData | null>(null);
 
   useEffect(() => {
-    setChartData(getChartData(data.level));
+    if (data.level) setChartData(getChartData(data.level));
```
Comment (dansvend) [inline components/common/molecules/TestResultItem.tsx:26]: The component is defined to always have a `data` object of `TestResult` type so this can be removed.

**Review by dansvend — CHANGES_REQUESTED** [review]

File: components/common/molecules/TestResultItem.tsx (hunk 2 above)
Comment (ofredstie) [reply components/common/molecules/TestResultItem.tsx]: Fixed

File: package.json [hunk 3]
```diff
@@ -39,7 +39,7 @@
     "prop-types": "^15.8.1",
     "react": "18.1.0",
     "react-dom": "18.1.0",
-    "react-native": "0.70.5",
+    "react-native": "0.70.8",
```
Comment (HaakonSvane) [inline package.json:42]: What caused this upgrade?
I see that the expo version is still the same and that the pipeline is failing. Might be related.

Try running fresh install locally and push any lockfile changes. Here is the fresh install script (from OM Inspection)
Screenshot 2023-05-24 at 08 52 52

**Review by HaakonSvane — CHANGES_REQUESTED** [review]

**Review by HaakonSvane — APPROVED** [review]
Looks nice 👍

**Review by dansvend — APPROVED** [review]
